[theme]
base = "light"
baseRadius = "none"
primaryColor = "white"
secondaryBackgroundColor = "white"
borderColor = "white"
showSidebarBorder = false
showWidgetBorder = false

[theme.sidebar]
backgroundColor = "#e4e4e4"

[client]
toolbarMode = "viewer"

[browser]
gatherUsageStats = false
